### ISSUE TITLE
- not supported during device registration

### ISSUE THREAD

**Issue by Emantor** [KronosKoderS/pypushover#37]
The `-` character is not supported during device registration e.g. `device_id = cm.register('Example-2')` does not work, `device_id = cm.register('Laptop')` works.
`-` and `_` are allowed per spec, I guess they need to be properly escaped for the URL.

**Comment by KronosKoderS** [comment]
Can you paste in your error tracing?  I just want to make sure I can properly reproduce the issue.

**Comment by Emantor** [comment]
```
>>> device_id = cm.register_device('Example-2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "py_pushover/client.py", line 167, in register_device
    self.latest_response_dict = send(self._register_device_url, data_out=params)
  File "py_pushover/_base.py", line 36, in send
    res.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.pushover.net/1/devices.json?secret=<secret>&os=O&name=Example-2```

**Comment by KronosKoderS** [comment]
I just ran a quick test:

class TestIssues(unittest.TestCase):
    def test_37_dash_support(self):
        cm = py_po.client.ClientManager(app_key)
        cm.login(email, pw)
        device_id = cm.register_device('Example-2')
        self.assertNotEqual(device_id, "")

and I'm not seeing what you're seeing

**Comment by Emantor** [comment]
Let me check this against master, I'm using the tar.gz atm, pip2 doesn't seem to install the package correctly (but that's probably my own issue).

**Comment by Emantor** [comment]
Works on master.

**Comment by KronosKoderS** [comment]
I have a few hotfixes to implement (mainly with trying to get pypushover to play nice enough to continue automated testing) and then I plan on pushing the update to pip.
