### ISSUE TITLE
How to handle stored messages

### ISSUE THREAD

**Issue by Emantor** [KronoSKoderS/pypushover#39]
At the moment the client instance saves retrieved messages but does not delete them after `clear_server_messages`. This makes it hard to store new messages as a client. I propose to empty `self.messages` after `clear_server_messages`, as the client should have saved them to local storage at this point.

**Comment by KronosKoderS** [comment]
https://github.com/KronosKoderS/pypushover/commit/c42dfc6ec42e4693502e303a122217965121061a

**Comment by KronosKoderS** [comment]
#42
